-- SQLite
--consulta capaz de exibir todos os funcionários e seus respectivos cargos
SELECT * FROM EMPLOYEES;
SELECT * FROM POSITIONS;

SELECT EMPLOYEES.ID,
       EMPLOYEES.NAME,
       EMPLOYEES.PHONE_NUMBER,
       EMPLOYEES.CONTRACT_DATE,
       POSITIONS.DESCRIPTION FROM EMPLOYEES

JOIN POSITIONS ON (EMPLOYEES.POSITION_ID = POSITIONS.ID);
